trigger:
- main

pool: self-hosted

variables:
  buildConfiguration: 'Release'

jobs: 
- job: dotnet_build
  displayName: Dotnet Build
  steps:
    - script: dotnet build ./src
      displayName: 'Build'
- job: docker_build
  displayName: Docker Build
  steps:
    - task: Docker@2
      displayName: 'Build'
      inputs:
        command: 'build'
        Dockerfile: './src/Books.Service.Web/Dockerfile'
        buildContext: '.'
- job: run_tests
  displayName: Run Tests
  steps:
    - script: docker-compose -f docker-compose-db-only.yaml pull
      displayName: 'Pull images'
    - script: docker-compose -f docker-compose-db-only.yaml rm -fs
      displayName: 'Stop and remove any existing containers'
    - script: docker-compose -f docker-compose-db-only.yaml up --build -d
      displayName: 'Create database container'
    - script: dotnet test ./src
      displayName: 'Run tests'   
    - script: docker-compose -f docker-compose-db-only.yaml stop -t 1
      displayName: 'Stop database container'