trigger:
- main

pool: atris-dev-local

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./src
  displayName: 'dotnet build'
- script: dotnet test ./src
  displayName: 'dotnet test'
