trigger:
- main

pool: atris-dev-local

variables:
  buildConfiguration: 'Release'

jobs: 
- job: 'dotnet-build-and-test'
  steps:
  - script: dotnet build ./src
    displayName: 'dotnet build'
  - script: dotnet test ./src
    displayName: 'dotnet test'
- job: 'docker-build-and-Test' 
  steps:
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: './src/Books.Service.Web/Dockerfile'
      buildContext: '.'
  - task: DockerCompose@0
    displayName: 'docker compose create database'
    inputs:
      action: 'Run services'
      dockerComposeFile: '**/docker-compose-db-only.yaml'
      buildImages: true
      detached: true