trigger:
- main

pool: atris-dev-local

variables:
  buildConfiguration: 'Release'

jobs: 
- job: dotnet_build
  displayName: Dotnet Build
  steps:
    - script: dotnet build ./src
      displayName: 'Build'
- job: docker_build
  displayName: Docker Build
  steps:
    - task: Docker@2
      displayName: 'Build'
      inputs:
        command: 'build'
        Dockerfile: './src/Books.Service.Web/Dockerfile'
        buildContext: '.'
- job: test
  displayName: Run Tests
  steps:
    - task: DockerCompose@0
      displayName: 'Create database'
      inputs:
        action: 'Run services'
        dockerComposeFile: '**/docker-compose-db-only.yaml'
        buildImages: true
        detached: true
    - script: dotnet test ./src
      displayName: 'Test'   