version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    container_name: books-api-test-mongodb
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: books-api
      MONGO_INITEXTRA_COLLECTIONNAME: Books
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb-test-data:/data/test-db
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d:ro
    
volumes:
  mongodb-test-data: null